### ISSUE TITLE
Allow Moving/Resizing On-Screen Touch Controls

### ISSUE THREAD

**Issue by PkmnTrnrGary** [OatmealDome/DolphiniOS-Issue-Tracker#43] opened 2020-02-27 00:38 UTC
Would love to see a feature added for moving/resizing touch controls. Not all hands are the same, so being able to customize those on-screen controls is a huge help to many people. Thanks!

**Comment by FuzzyNutz** [comment] 2020-02-27 02:51
I just made this request yesterday

**Comment by OatmealDome** [comment] 2020-03-09 17:11
Going to close as duplicate of #36 so we have one issue tracking all types of "controller editing".

**Closed by OatmealDome** 2020-03-09 17:11 UTC
Labels: feature request
